CREATE TABLE "city_new" (
  "id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
);

CREATE TABLE public.authority (
	"id" bigserial NOT NULL,
	"created_at" timestamptz NOT NULL,
	"updated_at" timestamptz NULL,
	"app_div" int4 NOT NULL,
	"name" varchar(50) NOT NULL,
	"key" varchar(50) NOT NULL,
	"order" int4 NOT NULL,
	CONSTRAINT authority_order_check CHECK ((order >= 0)),
	CONSTRAINT authority_pkey PRIMARY KEY ("id"),
);
