CREATE TABLE "city_new" (
  "id" int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  "name" varchar(255) NOT NULL,
  "description" varchar,
  "created_at" timestamp,
  "updated_at" timestamp
);
